from __future__ import annotations

from typing import Any, Dict

from conference.question_sets import QuestionDefinition, QuestionSet, merge_questions
from conference.question_sets.shared import (
    assets_question,
    career_stage_question,
    follow_up_interest_question,
    role_question,
)


STEP_ORDER = (
    "welcome",
    "role",
    "career_stage",
    "assets",
    "lab_discuss_interest",
    "lab_discussion_level",
    "lab_time_commitment",
    "lab_professional_responsibility",
    "lab_discussion_difficulty",
    "lab_success_expectation",
    "lab_discussion_format",
    "lab_question",
    "follow_up_interest",
    "identity",
    "review",
    "done",
)

FLOW_MODES: Dict[str, Dict[str, Any]] = {
    "quick": {
        "title": "Quick pulse",
        "detail": "~ 3 minutes · first laboratory signal",
        "accent": "📐",
        "steps": [
            "role",
            "lab_discuss_interest",
            "lab_time_commitment",
            "lab_question",
        ],
    },
    "standard": {
        "title": "Standard",
        "detail": "~ 5 minutes · discussion conditions",
        "accent": "🧭",
        "steps": [
            "role",
            "career_stage",
            "lab_discuss_interest",
            "lab_discussion_level",
            "lab_time_commitment",
            "lab_professional_responsibility",
            "lab_discussion_difficulty",
            "lab_question",
        ],
    },
    "deep": {
        "title": "Deep dive",
        "detail": "~ 7 minutes · fuller laboratory map",
        "accent": "🔬",
        "steps": [
            "role",
            "career_stage",
            "assets",
            "lab_discuss_interest",
            "lab_discussion_level",
            "lab_time_commitment",
            "lab_professional_responsibility",
            "lab_discussion_difficulty",
            "lab_success_expectation",
            "lab_discussion_format",
            "lab_question",
            "follow_up_interest",
        ],
    },
}

STEP_COPY = {
    "welcome": {
        "title": "D'Alembertiennes Lab Questionnaire",
        "body": "Climate, resources, research: is this a topic for the laboratory?",
        "note": "Anonymous first. Shared profile questions stay gentle; Dalembertiennes session questions stay local to this event.",
    },
    "role": {
        "title": "Role",
        "body": "Choose the perspectives you genuinely inhabit here.",
        "cta": "Continue",
    },
    "career_stage": {
        "title": "Career stage",
        "body": "Scientific trajectories start from different distances and tempos.",
        "cta": "Continue",
    },
    "assets": {
        "title": "Assets",
        "body": "Choose up to three things you could realistically bring into this discussion.",
        "cta": "Continue",
    },
    "lab_discuss_interest": {
        "title": "Q1 · Would you like to discuss this further?",
        "body": "Would you like these questions to be discussed within the laboratory?<br><br>By “these questions”, we mean climate, resources, energy, travel, the material conditions of research, collective decisions, and institutional responsibilities.",
        "cta": "Continue",
    },
    "lab_discussion_level": {
        "title": "Q2 · Level of discussion",
        "body": "In your opinion, what would be the right level for this discussion?<br><br>This asks where such a discussion should live: informally, inside the laboratory, or as part of its official collective life.",
        "cta": "Continue",
    },
    "lab_time_commitment": {
        "title": "Q3 · Time commitment",
        "body": "How much time could the laboratory reasonably devote to these questions?<br><br>This is about the legitimate amount of collective time, not only individual willingness.",
        "cta": "Continue",
    },
    "lab_professional_responsibility": {
        "title": "Q4 · Professional responsibilities",
        "body": "Do you think that reflecting on the climate, energy, or material impacts of research is part of your professional responsibilities?<br><br>This asks whether these reflections belong to professional life, institutional responsibility, or somewhere else.",
        "cta": "Continue",
    },
    "lab_discussion_difficulty": {
        "title": "Q5 · Difficulties in discussing this",
        "body": "What makes these questions difficult to discuss within the laboratory?<br><br>This helps identify the constraints that make the problem hard to formulate collectively.",
        "cta": "Continue",
    },
    "lab_success_expectation": {
        "title": "Q6 · Expectations",
        "body": "What would you expect from a successful collective discussion on these topics?<br><br>This asks what a useful discussion should produce, or deliberately not produce.",
        "cta": "Continue",
    },
    "lab_discussion_format": {
        "title": "Q7 · Format of discussion",
        "body": "Which discussion format would seem most appropriate to you?<br><br>Several formats may be useful. Choose the ones that would make the discussion most constructive.",
        "cta": "Continue",
    },
    "lab_question": {
        "title": "Q8 · Final open question",
        "body": "What question would you like to ask the laboratory about climate, resources, and research?<br><br>This is the question you would like the laboratory to face collectively.",
        "cta": "Continue",
    },
    "follow_up_interest": {
        "title": "Stay in touch?",
        "body": "If this line continues, would you like to be reachable for a follow-up?",
        "cta": "Continue",
    },
    "identity": {
        "title": "Alias or identity",
        "body": "Optional. Leave a name, affiliation, email, website, or remain anonymous.",
        "cta": "Continue",
    },
    "review": {
        "title": "Review before integrating",
        "body": "Shared profile answers can persist across events. Dalembertiennes session answers belong only to this laboratory questionnaire.",
        "cta": "Integrate",
    },
    "done": {
        "title": "Thank you.",
        "body": "The aim of this session is not to assume that the problem is already well defined. At laboratory scale, the first serious task may be to understand how to formulate the problem.",
        "cta": "Start again",
    },
}

QUESTION_SET = QuestionSet(
    id="dalembertiennes_v1",
    source_module=__name__,
    step_copy=STEP_COPY,
    step_order=STEP_ORDER,
    flow_modes=FLOW_MODES,
    questions=merge_questions(
        (
            role_question(
                "DALEMBERTIENNES_ROLE",
                prompt=STEP_COPY["role"]["title"],
                subtitle=STEP_COPY["role"]["body"],
            ),
            career_stage_question(
                "DALEMBERTIENNES_CAREER_STAGE",
                prompt=STEP_COPY["career_stage"]["title"],
                subtitle=STEP_COPY["career_stage"]["body"],
            ),
            assets_question(
                "DALEMBERTIENNES_ASSETS",
                prompt=STEP_COPY["assets"]["title"],
                subtitle=STEP_COPY["assets"]["body"],
            ),
            follow_up_interest_question(
                "DALEMBERTIENNES_FOLLOW_UP_INTEREST",
                prompt=STEP_COPY["follow_up_interest"]["title"],
                subtitle=STEP_COPY["follow_up_interest"]["body"],
            ),
        ),
        (
            QuestionDefinition(
                step="lab_discuss_interest",
                field="lab_discuss_interest",
                question_id="DALEMBERTIENNES_LAB_DISCUSS_INTEREST",
                prompt="Would you like these questions to be discussed within the laboratory?",
                subtitle="By “these questions”, we mean climate, resources, energy, travel, the material conditions of research, collective decisions, and institutional responsibilities.",
                input_type="single",
                options=(
                    {"value": "yes_definitely", "label": "Yes, definitely"},
                    {"value": "conditional_on_conditions", "label": "Depending on the conditions"},
                    {"value": "no_not_really", "label": "No, not really"},
                ),
                required=True,
                group="laboratory_discussion",
                subgroup="opening",
                free_text_field="lab_discuss_interest_detail",
                free_text_label="Any further details?",
            ),
            QuestionDefinition(
                step="lab_discussion_level",
                field="lab_discussion_level",
                question_id="DALEMBERTIENNES_LAB_DISCUSSION_LEVEL",
                prompt="In your opinion, what would be the right level for this discussion?",
                subtitle="This asks where such a discussion should live: informally, inside the laboratory, or as part of its official collective life.",
                input_type="single",
                options=(
                    {"value": "informal_interested_people", "label": "An informal discussion among interested people"},
                    {"value": "open_reflection_group", "label": "An open reflection group within the laboratory"},
                    {"value": "regular_lab_slot", "label": "A regular slot in the life of the laboratory"},
                    {"value": "officially_supported_lab", "label": "A discussion officially supported by the laboratory"},
                    {"value": "no_organized_discussion", "label": "I do not think this discussion needs to be organized"},
                ),
                required=False,
                group="laboratory_discussion",
                subgroup="opening",
                free_text_field="lab_discussion_level_detail",
                free_text_label="Any further details?",
            ),
            QuestionDefinition(
                step="lab_time_commitment",
                field="lab_time_commitment",
                question_id="DALEMBERTIENNES_LAB_TIME_COMMITMENT",
                prompt="How much time could the laboratory reasonably devote to these questions?",
                subtitle="This is about the legitimate amount of collective time, not only individual willingness.",
                input_type="single",
                options=(
                    {"value": "no_specific_time", "label": "No specific time"},
                    {"value": "one_off_yearly", "label": "A one-off moment, for example once a year"},
                    {"value": "approx_100_human_hours_per_year", "label": "Approximately 100 human-hours per year"},
                    {"value": "integrated_ordinary_decision_making", "label": "Time integrated into the laboratory’s ordinary decision-making"},
                ),
                required=True,
                group="laboratory_discussion",
                subgroup="opening",
                free_text_field="lab_time_commitment_other",
                free_text_label="Other",
            ),
            QuestionDefinition(
                step="lab_professional_responsibility",
                field="lab_professional_responsibility",
                question_id="DALEMBERTIENNES_LAB_PROFESSIONAL_RESPONSIBILITY",
                prompt="Do you think that reflecting on the climate, energy, or material impacts of research is part of your professional responsibilities?",
                subtitle="This asks whether these reflections belong to professional life, institutional responsibility, or somewhere else.",
                input_type="single",
                options=(
                    {"value": "yes_fully", "label": "Yes, fully"},
                    {"value": "yes_partly", "label": "Yes, partly"},
                    {"value": "conditional_on_clarity", "label": "Perhaps, but this is not clear today"},
                    {"value": "no_not_personal_level", "label": "No, not on a personal level"},
                    {"value": "other", "label": "Other"},
                ),
                required=False,
                group="laboratory_responsibility",
                subgroup="responsibility",
                free_text_field="lab_professional_responsibility_detail",
                free_text_label="Why?",
            ),
            QuestionDefinition(
                step="lab_discussion_difficulty",
                field="lab_discussion_difficulty",
                question_id="DALEMBERTIENNES_LAB_DISCUSSION_DIFFICULTY",
                prompt="What makes these questions difficult to discuss within the laboratory?",
                subtitle="This helps identify the constraints that make the problem hard to formulate collectively.",
                input_type="multi",
                max_select=3,
                options=(
                    {"value": "lack_time", "label": "Lack of time"},
                    {"value": "lack_clear_data", "label": "Lack of clear data"},
                    {"value": "fear_moral_judgment", "label": "Fear of moral judgment"},
                    {"value": "powerlessness", "label": "A feeling of powerlessness"},
                    {"value": "status_resources_constraints", "label": "Differences in status, resources, or constraints between people"},
                    {"value": "inappropriate_rules", "label": "The risk of creating inappropriate rules"},
                    {"value": "different_problem_definitions", "label": "The fact that not everyone defines the problem in the same way"},
                    {"value": "nothing_particular", "label": "Nothing in particular"},
                    {"value": "other", "label": "Other"},
                ),
                required=False,
                group="laboratory_constraints",
                subgroup="constraints",
                free_text_field="lab_discussion_difficulty_detail",
                free_text_label="Any further details?",
            ),
            QuestionDefinition(
                step="lab_success_expectation",
                field="lab_success_expectation",
                question_id="DALEMBERTIENNES_LAB_SUCCESS_EXPECTATION",
                prompt="What would you expect from a successful collective discussion on these topics?",
                subtitle="This asks what a useful discussion should produce, or deliberately not produce.",
                input_type="multi",
                max_select=3,
                options=(
                    {"value": "understand_real_impacts", "label": "To better understand the real impacts of our activities"},
                    {"value": "share_practical_constraints", "label": "To share the practical constraints people face"},
                    {"value": "identify_realistic_room_for_action", "label": "To identify realistic room for action"},
                    {"value": "avoid_individual_only_responsibility", "label": "To avoid placing responsibility only on individuals"},
                    {"value": "collective_recommendations", "label": "To produce collective recommendations"},
                    {"value": "decisions_or_rules", "label": "To produce decisions or rules"},
                    {"value": "reflection_without_immediate_decisions", "label": "To open a space for reflection without immediately seeking decisions"},
                    {"value": "low_expectation", "label": "I do not expect much from this type of discussion"},
                    {"value": "other", "label": "Other"},
                ),
                required=False,
                group="laboratory_expectations",
                subgroup="expectations",
                free_text_field="lab_success_expectation_detail",
                free_text_label="Any further details?",
            ),
            QuestionDefinition(
                step="lab_discussion_format",
                field="lab_discussion_format",
                question_id="DALEMBERTIENNES_LAB_DISCUSSION_FORMAT",
                prompt="Which discussion format would seem most appropriate to you?",
                subtitle="Several formats may be useful. Choose the ones that would make the discussion most constructive.",
                input_type="multi",
                max_select=3,
                options=(
                    {"value": "invited_presentations", "label": "Invited presentations"},
                    {"value": "open_debates", "label": "Open debates"},
                    {"value": "small_group_workshops", "label": "Small-group workshops"},
                    {"value": "concrete_feedback", "label": "Concrete feedback from teams or individuals"},
                    {"value": "lab_management_discussion", "label": "A discussion with the laboratory management"},
                    {"value": "parent_institutions_discussion", "label": "A discussion with the parent institutions"},
                    {"value": "anonymous_questions_concerns", "label": "An anonymous collection of questions and concerns"},
                    {"value": "other", "label": "Other"},
                ),
                required=False,
                group="laboratory_expectations",
                subgroup="formats",
                free_text_field="lab_discussion_format_detail",
                free_text_label="Any further details?",
            ),
            QuestionDefinition(
                step="lab_question",
                field="lab_question",
                question_id="DALEMBERTIENNES_LAB_QUESTION",
                prompt="What question would you like to ask the laboratory about climate, resources, and research?",
                subtitle="This is the question you would like the laboratory to face collectively.",
                input_type="text",
                required=False,
                placeholder="One question you would like the laboratory to face",
                group="laboratory_closing",
                subgroup="closing",
            ),
        ),
    ),
    profile_fields=(
        "role",
        "career_stage",
        "assets",
    ),
    session_fields=(
        "lab_discuss_interest",
        "lab_discuss_interest_detail",
        "lab_discussion_level",
        "lab_discussion_level_detail",
        "lab_time_commitment",
        "lab_time_commitment_other",
        "lab_professional_responsibility",
        "lab_professional_responsibility_detail",
        "lab_discussion_difficulty",
        "lab_discussion_difficulty_detail",
        "lab_success_expectation",
        "lab_success_expectation_detail",
        "lab_discussion_format",
        "lab_discussion_format_detail",
        "lab_question",
        "follow_up_interest",
        "boiler_room_contribution",
        "question_flags",
        "identity_reveal_targets",
    ),
    deferrable_fields=("lab_question",),
    fingerprint_axes=(),
    fingerprint_labels={},
    follow_up_contact_values=("yes", "maybe"),
    migration_profile_fields=("assets",),
)
