from __future__ import annotations

from models.questions import Question
from models.sessions import session_spec_by_id

QUESTION_CATALOG: list[Question] = [
    Question(
        id="ORGANISATION_SIGNAL",
        session_id="GLOBAL-SESSION",
        category="integration",
        context="First collective entry signal before entering the lobby.",
        prompt="Should we organise another event and continue the conversation?",
        qtype="pre_signal",
        options=[
            "Yes, let's continue the conversation",
            "Maybe, depending on conditions",
            "No, stop here",
        ],
        short_description=(
            "This first response sends a collective alignment signal. "
            "It helps shape the shared dynamics of the room."
        ),
        depth=0,
        required=True,
        visible_before_lobby=True,
        show_text_field=True,
        placeholder="Your condition or comment",
        order=1,
        active=True,
        response_mode="signal",
        response_structure=[
            "Yes — let’s continue",
            "Maybe — depending on conditions",
            "No — stop here",
        ],
        is_collective_signal=True,
    ),
    Question(
        id="ARRIVAL_EMOTION",
        session_id="GLOBAL-SESSION",
        category="perception",
        context="Initial emotional state of the room.",
        prompt="What emotion did you bring with you today?",
        qtype="single",
        options=[
            "Curious",
            "Hopeful",
            "Concerned",
            "Skeptical",
            "Overwhelmed",
            "Tired",
            "Inspired",
            "Neutral",
            "Other",
        ],
        short_description="Initial emotional state of the room.",
        depth=1,
        required=True,
        visible_before_lobby=True,
        order=2,
        active=True,
        response_mode="tags",
        response_structure=list(
            [
                "Curious",
                "Hopeful",
                "Concerned",
                "Skeptical",
                "Overwhelmed",
                "Tired",
                "Inspired",
                "Neutral",
                "Other",
            ]
        ),
    ),
    Question(
        id="ENVIRONMENT_CHANGE_EMOTION",
        session_id="GLOBAL-SESSION",
        category="perception",
        context="Affective framing of environmental transformation.",
        prompt="What emotion do you associate with changes in the natural world?",
        qtype="single",
        options=[
            "Awe",
            "Concern",
            "Urgency",
            "Sadness",
            "Responsibility",
            "Curiosity",
            "Detachment",
            "Other",
        ],
        depth=2,
        required=True,
        visible_before_lobby=True,
        order=3,
        active=True,
        response_mode="tags",
    ),
    Question(
        id="SOCIETAL_CHANGE_EMOTION",
        session_id="GLOBAL-SESSION",
        category="structure",
        context="Affective framing of social and institutional transformation.",
        prompt="What emotion do you associate with societal change?",
        qtype="single",
        options=[
            "Hope",
            "Anxiety",
            "Excitement",
            "Resistance",
            "Responsibility",
            "Uncertainty",
            "Trust",
            "Other",
        ],
        depth=3,
        required=True,
        visible_before_lobby=True,
        order=4,
        active=True,
        response_mode="tags",
    ),
    Question(
        id="COLLABORATION_READINESS",
        session_id="GLOBAL-SESSION",
        category="agency",
        context="Collective readiness to collaborate across differences.",
        prompt="Do you feel collaboration is possible across differences?",
        qtype="single",
        options=[
            "Yes — collaboration is possible",
            "Maybe — depending upon conditions",
            "No — differences are too strong",
            "Other",
        ],
        depth=4,
        required=True,
        visible_before_lobby=True,
        show_text_field=True,
        placeholder="Your condition or comment",
        order=5,
        active=True,
        response_mode="choice",
    ),
    Question(
        id="PERSONAL_AGENCY",
        session_id="GLOBAL-SESSION",
        category="agency",
        context="Perceived personal agency in collective decisions.",
        prompt="Do you feel able to influence collective decisions?",
        qtype="single",
        options=[
            "Yes",
            "Sometimes",
            "Rarely",
            "Not at all",
            "Other",
        ],
        depth=5,
        required=True,
        visible_before_lobby=True,
        order=6,
        active=True,
        response_mode="choice",
    ),
    Question(
        id="PERCEPTION_ENTRY",
        session_id="GLOBAL-SESSION",
        category="perception",
        context="Entry perception for the post-lobby interaction.",
        prompt="When you hear the word 'glacier', what comes first?",
        qtype="single",
        options=[
            "Landscape",
            "Sound",
            "Scientific object",
            "Symbol",
            "Warning",
            "Other",
        ],
        order=100,
        active=True,
    ),
    Question(
        id="PROXIMITY",
        session_id="GLOBAL-SESSION",
        category="perception",
        context="Self-positioning toward cryosphere impact.",
        prompt="Do glaciers feel distant or present in your life?",
        qtype="single",
        options=[
            "Distant abstraction",
            "Global but real",
            "Personally connected",
            "Structurally linked to my future",
        ],
        order=101,
        active=True,
    ),
    Question(
        id="EPISTEMIC_FRAME",
        session_id="GLOBAL-SESSION",
        category="structure",
        context="Interpretive frame for system dynamics.",
        prompt="Which description feels closer to reality?",
        qtype="single",
        options=[
            "Gradual slope",
            "Threshold or tipping point",
        ],
        order=102,
        active=True,
    ),
    Question(
        id="IRREVERSIBILITY_AFFECT",
        session_id="GLOBAL-SESSION",
        category="structure",
        context="Emotional response to irreversible transitions.",
        prompt="Irreversibility makes me feel...",
        qtype="multi",
        options=[
            "Fear",
            "Responsibility",
            "Motivation",
            "Powerlessness",
            "Clarity",
            "Curiosity",
        ],
        max_select=2,
        order=103,
        active=True,
    ),
    Question(
        id="PRIORITY_AFTER_NO_RETURN",
        session_id="GLOBAL-SESSION",
        category="agency",
        context="Priority setting under irreversible conditions.",
        prompt="When reversal is no longer possible, what becomes most important?",
        qtype="single",
        options=[
            "Speed",
            "Fairness",
            "Coordination",
            "Innovation",
            "Acceptance",
        ],
        order=104,
        active=True,
    ),
    Question(
        id="WHAT_ENABLES_ACTION",
        session_id="GLOBAL-SESSION",
        category="agency",
        context="Collective action enablers under uncertainty.",
        prompt="What helps societies act under uncertainty?",
        qtype="multi",
        options=[
            "Data",
            "Narratives",
            "Art",
            "Shared rituals",
            "Institutional rules",
            "Community belonging",
        ],
        max_select=2,
        order=105,
        active=True,
    ),
    Question(
        id="SHIFT_AFTER_PANEL",
        session_id="GLOBAL-SESSION",
        category="integration",
        context="Post-session framing shift.",
        prompt="After this session, glaciers feel more like...",
        qtype="single",
        options=[
            "Object of study",
            "Political issue",
            "Living system",
            "Mirror of society",
            "Call to responsibility",
        ],
        order=106,
        active=True,
    ),
    Question(
        id="ONE_WORD_TRACE",
        session_id="GLOBAL-SESSION",
        category="integration",
        context="Minimal residual trace after interaction.",
        prompt="One word that remains with you.",
        qtype="text",
        order=107,
        active=True,
        response_mode="text",
        response_structure={"max_length": 200},
    ),
    Question(
        id="IF_YOU_WERE_A_GLACIER",
        session_id="SESSION-1",
        category="integration",
        context="Give glaciers a direct voice in first person.",
        prompt="If you were a glacier, what would you say?",
        qtype="text",
        depth=1,
        order=1,
        active=True,
        response_mode="text",
        response_structure={"max_length": 200},
    ),
    Question(
        id="GLACIER_EMOTIONS",
        session_id="SESSION-1",
        category="perception",
        context="Capture emotional tones attached to glacier futures.",
        prompt="Which emotions describe your relation to glaciers right now?",
        qtype="multi",
        options=[
            "Curious",
            "Concerned",
            "Protective",
            "Conflicted",
            "Hopeful",
            "Overwhelmed",
        ],
        max_select=3,
        depth=1,
        order=2,
        active=True,
        response_mode="tags",
    ),
    Question(
        id="WORDS_TO_TAKE_WITH_YOU",
        session_id="SESSION-1",
        category="integration",
        context="Collect key terms participants want to carry forward.",
        prompt="What words do you want to take with you from this session?",
        qtype="multi",
        options=[
            "Care",
            "Repair",
            "Justice",
            "Responsibility",
            "Imagination",
            "Coordination",
        ],
        max_select=3,
        depth=2,
        order=3,
        active=True,
        response_mode="keywords",
        response_structure={"max_tags": 5},
    ),
    Question(
        id="SESSION2_PRIORITY_SIGNAL",
        session_id="SESSION-2",
        category="agency",
        context="Priority signal for the second experimental module.",
        prompt="For SESSION-2, what should we prioritize first?",
        qtype="single",
        options=[
            "Shared understanding",
            "Practical coordination",
            "Policy translation",
            "Local experimentation",
        ],
        depth=1,
        order=1,
        active=True,
        response_mode="choice",
    ),
    Question(
        id="SESSION2_OPEN_TRACE",
        session_id="SESSION-2",
        category="integration",
        context="Short open trace to close SESSION-2.",
        prompt="Name one condition needed to continue from SESSION-2.",
        qtype="text",
        depth=2,
        order=2,
        active=True,
        response_mode="text",
        response_structure={"max_length": 200},
    ),
]

QUESTION_BY_ID = {q.id: q for q in QUESTION_CATALOG}


def questions_for_session(
    session_code: str, *, include_inactive: bool = False
) -> list[Question]:
    code = (session_code or "").strip().upper()
    items = [q for q in QUESTION_CATALOG if q.session_id.upper() == code]
    if not include_inactive:
        items = [q for q in items if q.active]
    return sorted(items, key=lambda q: (q.order, q.depth, q.id))


def catalog_session_codes() -> list[str]:
    return sorted({q.session_id for q in QUESTION_CATALOG})


def validate_question_catalog() -> list[str]:
    errors: list[str] = []
    seen: set[str] = set()
    for q in QUESTION_CATALOG:
        if q.id in seen:
            errors.append(f"Duplicate question id: {q.id}")
        seen.add(q.id)
        if not session_spec_by_id(q.session_id):
            errors.append(f"Unknown session_id on question {q.id}: {q.session_id}")
        if q.order <= 0:
            errors.append(f"Question {q.id} must have order > 0")
        if q.response_type in {"choice", "tags", "keywords", "signal"} and not q.options:
            errors.append(f"Question {q.id} requires options for {q.response_type}")
    return errors
