from __future__ import annotations

from models.questions import Question

QUESTION_CATALOG: list[Question] = [
    Question(
        id="ORGANISATION_SIGNAL",
        category="integration",
        prompt="Should we organise another event and continue the conversation?",
        qtype="pre_signal",
        options=[
            "Yes, let's continue the conversation",
            "Maybe, depending on conditions",
            "No, stop here",
        ],
        short_description=(
            "This first response sends a collective alignment signal. "
            "It helps shape the shared dynamics of the room."
        ),
        depth=0,
        required=True,
        visible_before_lobby=True,
        show_text_field=True,
        placeholder="Your condition or comment",
    ),
    Question(
        id="ARRIVAL_EMOTION",
        category="perception",
        prompt="What emotion did you bring with you today?",
        qtype="single",
        options=[
            "Curious",
            "Hopeful",
            "Concerned",
            "Skeptical",
            "Overwhelmed",
            "Tired",
            "Inspired",
            "Neutral",
            "Other",
        ],
        short_description="Initial emotional state of the room.",
        depth=1,
        required=True,
        visible_before_lobby=True,
    ),
    Question(
        id="ENVIRONMENT_CHANGE_EMOTION",
        category="perception",
        prompt="What emotion do you associate with changes in the natural world?",
        qtype="single",
        options=[
            "Awe",
            "Concern",
            "Urgency",
            "Sadness",
            "Responsibility",
            "Curiosity",
            "Detachment",
            "Other",
        ],
        depth=2,
        required=True,
        visible_before_lobby=True,
    ),
    Question(
        id="SOCIETAL_CHANGE_EMOTION",
        category="structure",
        prompt="What emotion do you associate with societal change?",
        qtype="single",
        options=[
            "Hope",
            "Anxiety",
            "Excitement",
            "Resistance",
            "Responsibility",
            "Uncertainty",
            "Trust",
            "Other",
        ],
        depth=3,
        required=True,
        visible_before_lobby=True,
    ),
    Question(
        id="COLLABORATION_READINESS",
        category="agency",
        prompt="Do you feel collaboration is possible across differences?",
        qtype="single",
        options=[
            "Yes — collaboration is possible",
            "Maybe — depending upon conditions",
            "No — differences are too strong",
            "Other",
        ],
        depth=4,
        required=True,
        visible_before_lobby=True,
        show_text_field=True,
        placeholder="Your condition or comment",
    ),
    Question(
        id="PERSONAL_AGENCY",
        category="agency",
        prompt="Do you feel able to influence collective decisions?",
        qtype="single",
        options=[
            "Yes",
            "Sometimes",
            "Rarely",
            "Not at all",
            "Other",
        ],
        depth=5,
        required=True,
        visible_before_lobby=True,
    ),
    Question(
        id="PERCEPTION_ENTRY",
        category="perception",
        prompt="When you hear the word 'glacier', what comes first?",
        qtype="single",
        options=[
            "Landscape",
            "Sound",
            "Scientific object",
            "Symbol",
            "Warning",
            "Other",
        ],
    ),
    Question(
        id="PROXIMITY",
        category="perception",
        prompt="Do glaciers feel distant or present in your life?",
        qtype="single",
        options=[
            "Distant abstraction",
            "Global but real",
            "Personally connected",
            "Structurally linked to my future",
        ],
    ),
    Question(
        id="EPISTEMIC_FRAME",
        category="structure",
        prompt="Which description feels closer to reality?",
        qtype="single",
        options=[
            "Gradual slope",
            "Threshold or tipping point",
        ],
    ),
    Question(
        id="IRREVERSIBILITY_AFFECT",
        category="structure",
        prompt="Irreversibility makes me feel...",
        qtype="multi",
        options=[
            "Fear",
            "Responsibility",
            "Motivation",
            "Powerlessness",
            "Clarity",
            "Curiosity",
        ],
        max_select=2,
    ),
    Question(
        id="PRIORITY_AFTER_NO_RETURN",
        category="agency",
        prompt="When reversal is no longer possible, what becomes most important?",
        qtype="single",
        options=[
            "Speed",
            "Fairness",
            "Coordination",
            "Innovation",
            "Acceptance",
        ],
    ),
    Question(
        id="WHAT_ENABLES_ACTION",
        category="agency",
        prompt="What helps societies act under uncertainty?",
        qtype="multi",
        options=[
            "Data",
            "Narratives",
            "Art",
            "Shared rituals",
            "Institutional rules",
            "Community belonging",
        ],
        max_select=2,
    ),
    Question(
        id="SHIFT_AFTER_PANEL",
        category="integration",
        prompt="After this session, glaciers feel more like...",
        qtype="single",
        options=[
            "Object of study",
            "Political issue",
            "Living system",
            "Mirror of society",
            "Call to responsibility",
        ],
    ),
    Question(
        id="ONE_WORD_TRACE",
        category="integration",
        prompt="One word that remains with you.",
        qtype="text",
    ),
]

QUESTION_BY_ID = {q.id: q for q in QUESTION_CATALOG}
